### ISSUE TITLE
add better handling for unknown query answers

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/aitermis#14]
currently just prints "i dont' know to terminal" and asks if that should be executed (it can't be executed because it isn't a command". It should print something like "could not process query. please try again" and then exit the program

**Comment by JoNelson98** [comment]
i'll take up your issue

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find / contribute to this project

The documentation for this repository is still in the works, so please let me know if you're having any issues with setting things up!
